// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Models;

namespace WebApplication2.Migrations
{
    [DbContext(typeof(mesajcontext))]
    [Migration("20210407192738_Avioane")]
    partial class Avioane
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication2.Models.avion", b =>
                {
                    b.Property<int>("avionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("locatia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("avionId");

                    b.ToTable("hotels");
                });

            modelBuilder.Entity("WebApplication2.Models.beneficii", b =>
                {
                    b.Property<int>("beneficiiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bauturi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mancare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rezervareId")
                        .HasColumnType("int");

                    b.HasKey("beneficiiId");

                    b.HasIndex("rezervareId");

                    b.ToTable("beneficiis");
                });

            modelBuilder.Entity("WebApplication2.Models.cariera", b =>
                {
                    b.Property<int>("carieraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("avionId")
                        .HasColumnType("int");

                    b.Property<string>("calitati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("carieraId");

                    b.HasIndex("avionId");

                    b.ToTable("cariera");
                });

            modelBuilder.Entity("WebApplication2.Models.job", b =>
                {
                    b.Property<string>("jobId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("carieraId")
                        .HasColumnType("int");

                    b.Property<string>("experienta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numejob")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("jobId");

                    b.HasIndex("carieraId");

                    b.ToTable("joburi");
                });

            modelBuilder.Entity("WebApplication2.Models.mesaj", b =>
                {
                    b.Property<int>("mesajId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("avionId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mesajId");

                    b.HasIndex("avionId");

                    b.ToTable("mesaje");
                });

            modelBuilder.Entity("WebApplication2.Models.rezervare", b =>
                {
                    b.Property<int>("rezervareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Nrbilete")
                        .HasColumnType("int");

                    b.Property<int>("avionId")
                        .HasColumnType("int");

                    b.Property<int>("clasa")
                        .HasColumnType("int");

                    b.Property<string>("nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("rezervareId");

                    b.HasIndex("avionId");

                    b.ToTable("rezervari");
                });

            modelBuilder.Entity("WebApplication2.Models.beneficii", b =>
                {
                    b.HasOne("WebApplication2.Models.rezervare", "rezervare")
                        .WithMany("beneficii")
                        .HasForeignKey("rezervareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication2.Models.cariera", b =>
                {
                    b.HasOne("WebApplication2.Models.avion", "avion")
                        .WithMany("joburi")
                        .HasForeignKey("avionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication2.Models.job", b =>
                {
                    b.HasOne("WebApplication2.Models.cariera", "cariera")
                        .WithMany("joburi")
                        .HasForeignKey("carieraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication2.Models.mesaj", b =>
                {
                    b.HasOne("WebApplication2.Models.avion", "avion")
                        .WithMany("mesaje")
                        .HasForeignKey("avionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication2.Models.rezervare", b =>
                {
                    b.HasOne("WebApplication2.Models.avion", "avion")
                        .WithMany("rezervari")
                        .HasForeignKey("avionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
